In [1]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv("D:/Python/Datasets/retail_sales_messy_challenge.csv")

In [5]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer       82 non-null     object
 1   Region         81 non-null     object
 2   Channel        82 non-null     object
 3   Customer_Type  81 non-null     object
 4   Orders         82 non-null     int64
 5   AOV            82 non-null     int64
 6   Order_Date     82 non-null     object
 7   Sales          81 non-null     object
 8   Profit_Margin  82 non-null     float64
 9   Profit         81 non-null     float64
dtypes: float64(2), int64(2), object(6)
memory usage: 6.5+ KB

In [7]:
retail.shape

(82, 10)

In [9]:
retail.head()

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
0,C004,East,Store,Regular,4,15015,07-01-2026,60060.0,15.9,9550.0
1,C020,East,Store,Regular,15,11761,13-02-2026,176415.0,17.8,31402.0
2,C015,East,Store,High Value,16,8815,01-02-2026,125000,13.9,19605.0
3,C047,East,ONLINE,High Value,27,12446,15-04-2026,336042.0,18.4,61832.0
4,C011,East,Store,High Value,26,15089,23-01-2026,392314.0,15.5,60809.0

In [17]:
# The goal is to clean the data and define the business outcomes.
# First clean the data, find the missing, duplicate, unique values.
retail.isna().sum() # this shows the number of missing values in each column

Customer         0
Region           1
Channel          0
Customer_Type    1
Orders           0
AOV              0
Order_Date       0
Sales            1
Profit_Margin    0
Profit           1
dtype: int64

In [19]:
retail.duplicated().sum() # this shows the number of duplicatde rows

2

In [15]:
retail[retail.duplicated()]

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
33,C048,East,Store,High Value,20,10893,18-04-2026,217860.0,17.4,37908.0
66,C013,North,Store,Regular,25,6824,28-01-2026,170600.0,29.8,50839.0

In [21]:
retail[retail.duplicated(keep=False)]

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
27,C048,East,Store,High Value,20,10893,18-04-2026,217860.0,17.4,37908.0
33,C048,East,Store,High Value,20,10893,18-04-2026,217860.0,17.4,37908.0
47,C013,North,Store,Regular,25,6824,28-01-2026,170600.0,29.8,50839.0
66,C013,North,Store,Regular,25,6824,28-01-2026,170600.0,29.8,50839.0

In [23]:
retail['Channel'].unique()

array([' Store ', 'Store', 'ONLINE', 'Online', 'online', 'online ',
       ' store'], dtype=object)

In [25]:
retail['Customer_Type'].unique()

array(['Regular', 'High Value', nan], dtype=object)

In [27]:
retail['Region'].unique()

array(['East', 'North', 'West', 'South', 'south', 'NORTH ', nan,
       ' South '], dtype=object)

In [29]:
retail['Region'] = retail['Region'].str.lower().str.strip().str.title()
#this alters the values to title case and trims the spaces

In [31]:
retail['Region'].unique()

array(['East', 'North', 'West', 'South', nan], dtype=object)

In [33]:
retail['Channel'] = retail['Channel'].str.title().str.strip()

In [35]:
retail['Channel'].unique()

array(['Store', 'Online'], dtype=object)

In [37]:
retail['Sales'] = pd.to_numeric(retail['Sales'], errors = 'coerce')
#sales values are in string data type, so converting them to numberic datatype

In [47]:
retail['Sales'].isna().sum()
# this says that the sales column has 2 missing values

2

In [45]:
retail[retail['Sales'].isna()]
# this shows that the rows where sales value is missing, Profit margin and profit are present.
# so instead of replace the missing values with mean value, we will use the columns to construct the sales value.

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
11,C037,North,Store,Regular,26,8819,24-03-2026,NaN,12.7,29120.0
18,C009,North,Online,High Value,5,6275,19-01-2026,NaN,27.6,8660.0

In [49]:
retail.loc[retail["Sales"].isna(), "Sales"] = (
    retail.loc[retail["Sales"].isna(), "Profit"]
    / retail.loc[retail["Sales"].isna(), "Profit_Margin"]
    * 100
)

In [51]:
retail['Sales'].isna().sum()

0

In [53]:
retail["Profit"].isna().sum()

1

In [55]:
retail[retail["Profit"].isna()]
# profit can be calculated for this row.

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
6,C024,West,Online,Regular,25,9005,22-02-2026,225125.0,14.7,NaN

In [57]:
retail.loc[retail['Profit'].isna(),'Profit']= (
    retail.loc[retail['Profit'].isna(),'Sales']
    * retail.loc[retail['Profit'].isna(), 'Profit_Margin']
    * 100)

In [59]:
retail["Profit"].isna().sum()

0

In [63]:
retail[retail.duplicated(keep=False)]

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
27,C048,East,Store,High Value,20,10893,18-04-2026,217860.0,17.4,37908.0
33,C048,East,Store,High Value,20,10893,18-04-2026,217860.0,17.4,37908.0
47,C013,North,Store,Regular,25,6824,28-01-2026,170600.0,29.8,50839.0
66,C013,North,Store,Regular,25,6824,28-01-2026,170600.0,29.8,50839.0

In [65]:
# we see 2 duplicate rows in the entire dataset, so decided to drop them.
retail = retail.drop_duplicates()

In [67]:
retail.shape

(80, 10)

In [69]:
# we have to convert the order date from object data type to datetime data type.
retail['Order_Date'] = pd.to_datetime(retail['Order_Date'], dayfirst = True)

C:\Users\saiki\AppData\Local\Temp\ipykernel_15228\3788292188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail['Order_Date'] = pd.to_datetime(retail['Order_Date'], dayfirst = True)

In [71]:
retail['Order_Date'].dtype

dtype('<M8[ns]')

In [75]:
retail.info()
# this shows that the region and customer type columns has 1 missing value each.

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 0 to 81
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer       80 non-null     object
 1   Region         79 non-null     object
 2   Channel        80 non-null     object
 3   Customer_Type  79 non-null     object
 4   Orders         80 non-null     int64
 5   AOV            80 non-null     int64
 6   Order_Date     80 non-null     datetime64[ns]
 7   Sales          80 non-null     float64
 8   Profit_Margin  80 non-null     float64
 9   Profit         80 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 6.9+ KB

In [77]:
retail[retail['Region'].isna()]

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
35,C052,NaN,Online,Regular,13,13909,2026-04-27,180817.0,22.9,41407.0

In [79]:
retail[retail['Customer_Type'].isna()]

,Customer,Region,Channel,Customer_Type,Orders,AOV,Order_Date,Sales,Profit_Margin,Profit
46,C071,West,Online,NaN,24,11854,2026-06-09,284496.0,20.2,57468.0

In [83]:
# here we cannot replace the mode value with the missing region value as that doesn't make any sense.
# lets understand the if there is any relation with the columns to decide the customer type.
retail['Customer_Type'].value_counts()

Customer_Type
Regular       52
High Value    27
Name: count, dtype: int64

In [85]:
retail.groupby('Customer_Type')[["Sales", "Orders", "AOV"]].mean()

                       Sales     Orders           AOV
Customer_Type
High Value     191020.474503  17.296296  10663.259259
Regular        173669.660357  16.480769  10545.115385

In [87]:
retail.groupby("Customer_Type")["Sales"].agg(["min", "max"])

                   min       max
Customer_Type
High Value     21436.0  431872.0
Regular        30390.0  390850.0

In [89]:
retail.groupby("Customer_Type")["Orders"].agg(["min", "max"])

               min  max
Customer_Type
High Value       4   30
Regular          4   29

In [91]:
# the above analysis doesn't show any relation in defiing the customer type, so it's better to drop the 2 rows.
retail = retail.dropna(subset=["Region", "Customer_Type"])

In [93]:
retail.shape

(78, 10)

In [95]:
# To summarize the data cleaning:
# we have cleaned the region, customer_type and region columns and dropped the missing values rows.
# Converted the datatype of sales and order date columns.
# Calculated the missing values of sales and profit columns.

In [99]:
retail.nlargest(5, "Profit")[["Customer", "Sales", "Profit", "Profit_Margin"]]
# this shows a issue in the data.
# for customer C024, we see an issue in the Profit calculation.

   Customer     Sales       Profit  Profit_Margin
6      C024  225125.0  330933750.0           14.7
12     C018  411129.0     120461.0           29.3
30     C069  390850.0     105139.0           26.9
23     C046  431872.0     101922.0           23.6
42     C027  375310.0     101709.0           27.1

In [101]:
retail["Expected_Profit"] = (
    retail["Sales"] * retail["Profit_Margin"] / 100
)

retail["Profit_Difference"] = (
    retail["Profit"] - retail["Expected_Profit"]
)

In [105]:
retail.nlargest(5, "Profit_Difference")[
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Expected_Profit", "Profit_Difference"]
]
# this shows a difference in the profit values after the calculation.

,Customer,Sales,Profit,Profit_Margin,Expected_Profit,Profit_Difference
6,C024,225125.0,330933750.0,14.7,33093.375,3.309007e+08
2,C015,125000.0,19605.0,13.9,17375.000,2.230000e+03
50,C056,262242.0,48253.0,18.4,48252.528,4.720000e-01
77,C049,140022.0,28845.0,20.6,28844.532,4.680000e-01
17,C044,210176.0,23330.0,11.1,23329.536,4.640000e-01

In [107]:
retail["Calculated_Margin"] = (
    retail["Profit"] / retail["Sales"] * 100
)

retail["Margin_Difference"] = (
    retail["Calculated_Margin"] - retail["Profit_Margin"]
)

In [109]:
retail.nlargest(5, "Margin_Difference")[
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Calculated_Margin", "Margin_Difference"]
]

,Customer,Sales,Profit,Profit_Margin,Calculated_Margin,Margin_Difference
6,C024,225125.0,330933750.0,14.7,147000.000000,146985.300000
2,C015,125000.0,19605.0,13.9,15.684000,1.784000
25,C050,44433.0,10531.0,23.7,23.700853,0.000853
0,C004,60060.0,9550.0,15.9,15.900766,0.000766
43,C068,43491.0,10873.0,25.0,25.000575,0.000575

In [111]:
retail.nsmallest(5, "Margin_Difference")[
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Calculated_Margin", "Margin_Difference"]
]

,Customer,Sales,Profit,Profit_Margin,Calculated_Margin,Margin_Difference
5,C059,185000.0,9850.0,25.5,5.324324,-20.175676
29,C058,30390.0,6959.0,22.9,22.898980,-0.001020
26,C043,59292.0,9012.0,15.2,15.199352,-0.000648
37,C055,107074.0,26768.0,25.0,24.999533,-0.000467
55,C070,133020.0,36580.0,27.5,27.499624,-0.000376

In [113]:
# we found the issue in the profit calculation in the top 5 and bottom 5 values so we have to check the entire for the issue.
retail[retail["Profit_Difference"].abs() > 10][
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Expected_Profit", "Profit_Difference"]
]

,Customer,Sales,Profit,Profit_Margin,Expected_Profit,Profit_Difference
2,C015,125000.0,19605.0,13.9,17375.000,2.230000e+03
5,C059,185000.0,9850.0,25.5,47175.000,-3.732500e+04
6,C024,225125.0,330933750.0,14.7,33093.375,3.309007e+08

In [115]:
#since we found the issue in only these 3 rows lets calculate the profit for these 3 rows and replace it.
retail.loc[retail["Customer"].isin(["C024", "C015", "C059"]), "Profit"] = (
    retail.loc[retail["Customer"].isin(["C024", "C015", "C059"]), "Sales"]
    * retail.loc[retail["Customer"].isin(["C024", "C015", "C059"]), "Profit_Margin"]
    / 100
)

In [117]:
retail.nlargest(5, "Margin_Difference")[
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Calculated_Margin", "Margin_Difference"]
]

,Customer,Sales,Profit,Profit_Margin,Calculated_Margin,Margin_Difference
6,C024,225125.0,33093.375,14.7,147000.000000,146985.300000
2,C015,125000.0,17375.000,13.9,15.684000,1.784000
25,C050,44433.0,10531.000,23.7,23.700853,0.000853
0,C004,60060.0,9550.000,15.9,15.900766,0.000766
43,C068,43491.0,10873.000,25.0,25.000575,0.000575

In [121]:
retail.nsmallest(5, "Margin_Difference")[
    ["Customer", "Sales", "Profit", "Profit_Margin",
     "Calculated_Margin", "Margin_Difference"]
]

,Customer,Sales,Profit,Profit_Margin,Calculated_Margin,Margin_Difference
5,C059,185000.0,47175.0,25.5,5.324324,-20.175676
29,C058,30390.0,6959.0,22.9,22.898980,-0.001020
26,C043,59292.0,9012.0,15.2,15.199352,-0.000648
37,C055,107074.0,26768.0,25.0,24.999533,-0.000467
55,C070,133020.0,36580.0,27.5,27.499624,-0.000376

In [123]:
# as the profit calculation corrected now, lets drop the diagnostic columns
retail = retail.drop(columns=[
    "Expected_Profit",
    "Profit_Difference",
    "Calculated_Margin",
    "Margin_Difference"
])

In [125]:
#Now the data is clean and ready to derive the business outcomes.

In [127]:
# Calculate the Total Sales
total_sales = retail['Sales'].sum()
print('Total Sales = ', round(total_sales,2))

Total Sales =  14007558.15

In [129]:
# Calculate the Total Profit
total_profit = retail['Profit'].sum()
print('Total Profit = ', round(total_profit,2))

Total Profit =  2932145.38

In [131]:
# Calculate the Total Orders
total_orders = retail['Orders'].sum()
print('Total Orders = ', total_orders)

Total Orders =  1311

In [133]:
#Calculate Overall Profit Margin
overall_profit_margin = retail['Profit'].sum() / retail['Sales'].sum() * 100
print('Overall Profit Margin = ',round(overall_profit_margin,2))

Overall Profit Margin =  20.93

In [155]:
# Region with Highest sales and profit
regional = retail.groupby("Region")[["Sales", "Profit"]].sum()

In [159]:
regional["Profit_Margin"] = regional["Profit"] / regional["Sales"] * 100

In [163]:
regional
# West is the largest contributor in absolute financial terms, while South converts a larger percentage of its sales into profit.

               Sales      Profit  Profit_Margin
Region
East    2.650213e+06  499921.000      18.863427
North   4.134954e+06  870717.000      21.057477
South   2.575415e+06  579611.000      22.505538
West    4.646976e+06  981896.375      21.129792

In [165]:
# How does Online compare with Store?
# Calculate total sales, profit, average AOV and profit margin across the channels.

In [171]:
#Total Sales and Profit across channels
channels = retail.groupby('Channel')[['Sales','Profit']].sum()

In [173]:
channels

                Sales       Profit
Channel
Online   6.686458e+06  1403681.375
Store    7.321100e+06  1528464.000

In [169]:
# Average AOV across the channels
retail.groupby('Channel')['AOV'].mean()

Channel
Online    10006.692308
Store     11079.076923
Name: AOV, dtype: float64

In [175]:
channels['profit_margin'] = channels['Profit'] / channels['Sales'] * 100

In [179]:
channels
# channel generating more revenue also generates more absolute profit
# while the two channels have almost identical profitability rates
# so I wouldn't make a strong claim that one channel is materially more profitable

                Sales       Profit  profit_margin
Channel
Online   6.686458e+06  1403681.375      20.992900
Store    7.321100e+06  1528464.000      20.877517

In [181]:
# Are our High Value customers actually more valuable than Regular customers?
# Analysis based on the customer type.

In [187]:
retail.groupby('Customer_Type')['Customer'].count()

Customer_Type
High Value    27
Regular       51
Name: Customer, dtype: int64

In [191]:
retail.groupby('Customer_Type')[['Sales','Orders']].sum()

                      Sales  Orders
Customer_Type
High Value     5.157553e+06     467
Regular        8.850005e+06     844

In [199]:
retail.groupby('Customer_Type')[['Sales','Orders', 'AOV', 'Profit_Margin']].mean()

                       Sales     Orders           AOV  Profit_Margin
Customer_Type
High Value     191020.474503  17.296296  10663.259259      19.651852
Regular        173529.516443  16.549020  10479.156863      21.319608

In [201]:
# High Value customers generate higher revenue per customer, but the difference is relatively modest. Their advantage comes from slightly higher order frequency and AOV.
# However, Regular customers have a higher average profit margin, so High Value customers are not necessarily more profitable on a percentage basis.

In [211]:
# Which month generated the highest and lowest Sales?
retail['month'] = retail['Order_Date'].dt.month_name()

In [215]:
monthly_sales = retail.groupby('month')['Sales'].sum()

In [225]:
monthly_sales = monthly_sales.sort_values(ascending = False)
print(monthly_sales)

month
January     2.774266e+06
April       2.487187e+06
February    2.485974e+06
March       2.243363e+06
June        2.027527e+06
May         1.989241e+06
Name: Sales, dtype: float64

In [229]:
# How dependent are we on our largest customers for revenue?

In [231]:
top_10_customers = retail.nlargest(10,'Sales')

In [239]:
top_10_customers['Sales'].sum() / retail['Sales'].sum() * 100

26.587553377052892

In [241]:
# The top 10 customers contribute approximately 26.59% of total company Sales.
# About one-quarter of the company's revenue comes from just 10 customers.

In [243]:
# FInal recommendations of this analysis
# 1) Investigate why East has the lowest margin at 18.86% before pursuing additional growth.
# 2) Online and Store have almost identical margins (~21%), so channel strategy should consider Sales, AOV, customer behavior and growth—not margin alone.
# 3) High Value customers generate somewhat higher revenue per customer, but their margin is lower. Target Regular customers with potential to increase frequency/AOV while protecting margin.
# 4) The top 10 customers generate 26.6% of Sales while representing only 12.8% of customers. Developing the next customer tier can broaden the revenue base.